# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_object_id', models.PositiveIntegerField()),
                ('published_object_id', models.PositiveIntegerField(null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='publishable',
            unique_together=set([('content_type', 'draft_object_id')]),
        ),
    ]
