# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_article_drafts', '0002_publishable_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishable',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
